apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-nginx-conf
  namespace: ecom-05
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;

        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
        }

        location /api/ {
            proxy_pass http://ecommerce-api-service:8080;
            proxy_connect_timeout 3s;
            proxy_read_timeout 3s;
        }
    }
